temp/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>85</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <label>Manager Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skills_Required__c</fullName>
        <label>Skills Required</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Job Advertisement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateRecords.cls
public with sharing class CreateRecords {
    public static void createTestRecord(Integer count, String status) {
        List<Job_advertisement__c> jobs = new List<Job_Advertisement__c>();
        for(Integer i=0; i<count; i++){
            Job_Advertisement__c job = new Job_advertisement__c();
            job.Name = status + 'Job ' + i;
            job.Status__c = status;
            job.Description__c = status + 'job' + i + 'description';
            job.Location__c = status + ' job' + i + 'location';
            job.Education__c = status + ' job' + i + 'education';
            job.Salary__c = '50K - 75K';
            job.Manager_Name__c = 'Viktoriia Yefimova';
            job.Phone__c = '06685978122';
            job.Email__c = 'vikaephimova1996@gmail.com';
            job.Skills_Required__c = status + 'job' + i + 'skills required';
            jobs.add(job);
        }
        insert jobs;
    }
}